from enum import Enum
from typing import Protocol, runtime_checkable
import numpy as np


class Transition(str, Enum):
    CONTINUE = "CONTINUE"
    SWITCH = "SWITCH"
    RETURN = "RETURN"
    NEW = "NEW"
    CLARIFY = "CLARIFY"


@runtime_checkable
class LLM(Protocol):
    def propose(self, prompt: str, schema: dict) -> dict: ...
    def generate(self, prompt: str) -> str: ...
    def embed(self, texts: list[str]) -> list["np.ndarray"]: ...


@runtime_checkable
class Registry(Protocol):
    def add(self, t) -> None: ...
    def get(self, id: str): ...
    def all(self) -> list: ...
    def open_tasks(self) -> list: ...
    def active(self): ...
    def mark_active(self, id: str, turn: int) -> None: ...
    def record_mention(self, task_id: str, turn: int, loop_id: str | None = None) -> None: ...
    def last_selected_referent(self) -> str | None: ...
    def set_last_selected_referent(self, referent_id: str | None) -> None: ...
    def apply_update(self, id: str, delta: dict) -> None: ...
